fix: add start method
libp2p/js-libp2p-ping pull request #69
Opened 2018-03-26 09:55 UTC by JGAntunes

The lack of start implies that events might get lost since we have no way of setting up handlers before `ping` starts emitting.

2018-03-26 16:58 UTC, JGAntunes commented
@diasdavid if you could review this when you have some please :point_up:

2018-03-26 17:34 UTC, daviddias requested changes
No tests? What was failing?

2018-03-29 00:43 UTC, JGAntunes commented
@diasdavid what happens is that the ping may start emitting events before handlers can be setup. Specifically - https://github.com/JGAntunes/js-ipfs/blob/feat/ping/src/core/components/ping.js#L65 - this error may not be caught since this - https://github.com/libp2p/js-libp2p-ping/blob/master/src/ping.js#L28 - might execute before the handlers are registered.
I can try to add tests to this but it's just that it looks like a kind of a complicate race condition that comes from the way the module is structured.

2018-04-23 08:06 UTC, diasdavid commented
@JGAntunes the event emitter is created before .start is called, you can always set up the handler there. Am I missing something?

2018-04-23 08:07 UTC, merged

2018-04-23 09:02 UTC, JGAntunes commented
@diasdavid sorry, I'm not following, before you had no start, which meant that the `swarm.dial` would be called on ping construction and stuff like this - https://github.com/libp2p/js-libp2p-ping/blob/v0.7.0/src/ping.js#L28 - for example could be emitted before you had time to setup event handlers.